<a href="https://colab.research.google.com/github/mr-amit-yadav/Data-Analysis-with-Python/blob/main/Numpy_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
Numpy is a fundamental libraray for scientific computing in Python.<br>
It provides support for arrays and matrices,along with a collection of mathematical functions to operate on these data structures.

In [ ]:
import numpy as np

## Create array using numpy
## Create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
# 1D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
# 2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
np.arange(0,10,2).reshape(5,1) # 5 represents rows and 1 represents columns

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## Idenity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of Numpy Array
arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of Dimensions:",arr.ndim)
print("Size (number of elements):",arr.size)
print("Data Type:",arr.dtype)
print("Item Size (in Bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
Size (number of elements): 6
Data Type: int64
Item Size (in Bytes): 8


In [ ]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element wise Addition
print("Addition:",arr1+arr2)

## Element wise Subtraction
print("Subtraction:",arr1-arr2)

## Element wise Multiplication
print("Multiplication:",arr1*arr2)

## Element wise Division
print("Divison:",arr1/arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Divison: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## Universal Function
arr=np.array([2,3,4,5,6])

## Square Root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## Natrural Log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
## Array Slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [ ]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [ ]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [ ]:
## Modify the array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
### Statistical Concepts -- Normalization
## To have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])

# Calculate Mean and Standard Deviation
mean=np.mean(data)
std_dev = np.std(data)

# Normalize the data
noramalized_data=(data-mean)/std_dev
print("Noramalized Dta:", noramalized_data)

Noramalized Dta: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
# Some Statistical Concepts
data=np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean=np.mean(data)
print("Mean:",mean)

# Median
median=np.median(data)
print("Median:",median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)

# Variance
Variance=np.var(data)
print("Variance:",Variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
# Logical Operations
data=np.array([1,2,3,4,5,6,7,8,9])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])